- name: Ensure apt cache is updated
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install required packages
  apt:
    name:
      - nginx
      - python3-pip
      - unzip
      - snapd
    state: present
    update_cache: yes
- name: Ensure certbot is installed via snap
  command: snap install --classic certbot
  args:
    creates: /snap/bin/certbot
- name: Create symlink for certbot
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
- name: Ensure deployment directory exists
  file:
    path: /var/www/react
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
- name: Deploy nginx config
  template:
    src: nginx.react.j2
    dest: /etc/nginx/sites-available/react
    owner: root
    group: root
    mode: '0644'
- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/react
    dest: /etc/nginx/sites-enabled/react
    state: link
    force: yes
- name: Remove default nginx conf if exists
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: Test nginx config
  command: nginx -t
  register: nginx_test
  failed_when: nginx_test.rc != 0
- name: Restart nginx
  service:
    name: nginx
    state: restarted
