- name: Prepare web server
  hosts: web
  become: yes
  roles:
    - react_web

- name: Deploy built assets
  hosts: web
  become: yes
  tasks:
    - name: Copy build artifact to remote server
      copy:
        src: /tmp/react_build.tar.gz
        dest: /tmp/react_build.tar.gz

    - name: Unpack artifact to deployment dir
      unarchive:
        src: /tmp/react_build.tar.gz
        dest: /var/www/react
        remote_src: yes
        owner: www-data
        group: www-data
